### ISSUE TITLE
我是數學老師，有這個機會學習Python，太棒了。

### ISSUE THREAD

**Issue by yehtzuchun** [peculab/PythonAI4Beginners#12]
[看到有學生有python來解決三角函數問題，太好了](https://colab.research.google.com/drive/1h1BZTMoN6RbZHOLFuTmdl9TXpIEsEq3F)

**Comment by maiarafag** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
